name: Test

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  test:
    name: Just a little test
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    permissions:
      pull-requests: write

    steps:
      - name: Test
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('test');
